#!/usr/bin/env node
/**
 * launch-check.mjs
 *
 * Comprehensive pre-launch CI scan for ConnectSphere mobile.
 * Run before every TestFlight / production EAS build:
 *
 *   node scripts/launch-check.mjs
 *
 * Exits 0 on clean pass, 1 on any failure.
 * No external dependencies — uses only Node.js built-ins.
 *
 * Checks performed:
 *  A. Required environment variables present
 *  B. Dev-only flags are OFF
 *  C. Sound asset files exist and are non-empty (not placeholder-only)
 *  D. Firebase native config files present (google-services / GoogleService-Info)
 *  E. eas.json has a "production" profile with env block
 *  F. No hardcoded localhost / 127.0.0.1 in source files
 *  G. No TODO/FIXME/HACK comments in critical production paths
 *  H. app.json has required fields (name, slug, version, ios.bundleIdentifier, android.package)
 *  I. No committed .env files with real secrets
 *  J. TypeScript reports zero errors (requires tsc on PATH — skipped if not found)
 */

import { execSync } from "child_process";
import { existsSync, readFileSync, readdirSync, statSync } from "fs";
import { join, relative } from "path";
import { fileURLToPath } from "url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));

// ── Helpers ───────────────────────────────────────────────────────────────────

const failures = [];
const warnings = [];

function fail(msg) { failures.push(`  ✗ ${msg}`); }
function warn(msg) { warnings.push(`  ⚠ ${msg}`); }
function pass(msg) { console.log(`  ✓ ${msg}`); }
function flagEnabled(value) {
  return typeof value === "string" && ["1", "true", "yes", "on", "enabled"].includes(value.trim().toLowerCase());
}

function readJson(filePath) {
  try { return JSON.parse(readFileSync(filePath, "utf8")); }
  catch { return null; }
}

/** Recursively collect .ts/.tsx files, skipping node_modules / .expo / dist */
function collectSrc(dir, acc = []) {
  let entries;
  try { entries = readdirSync(dir); } catch { return acc; }
  for (const entry of entries) {
    if (["node_modules", ".expo", "dist", ".git", "functions"].includes(entry)) continue;
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) collectSrc(full, acc);
    else if (/\.(ts|tsx)$/.test(entry)) acc.push(full);
  }
  return acc;
}

// ── A. Required env vars ──────────────────────────────────────────────────────

console.log("\n[A] Required environment variables");

const REQUIRED_ENV = [
  "EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY",
  "EXPO_PUBLIC_API_URL",
  "EXPO_PUBLIC_API_BASE_URL",
  "EXPO_PUBLIC_REVENUECAT_IOS_API_KEY",
  "EXPO_PUBLIC_REVENUECAT_ANDROID_API_KEY",
  "EXPO_PUBLIC_SENTRY_DSN",
  "EXPO_PUBLIC_PROJECT_ID",
];

for (const key of REQUIRED_ENV) {
  const val = process.env[key];
  if (!val) {
    fail(`${key} is not set`);
  } else if (
    val.includes("YOUR_") ||
    val.includes("PLACEHOLDER") ||
    val === "TODO" ||
    val.startsWith("pk_test_")       // Clerk test key in prod
  ) {
    fail(`${key} looks like a placeholder: "${val}"`);
  } else {
    pass(key);
  }
}

// ── B. Dev-only flags OFF ─────────────────────────────────────────────────────

console.log("\n[B] Dev-only flags");

const devFlags = {
  EXPO_PUBLIC_ENABLE_DEMO_SEEDS: "demo seeds",
  EXPO_PUBLIC_CONNECTSPHERE_LOCAL_DB_FALLBACK: "local DB fallback",
};

for (const [key, label] of Object.entries(devFlags)) {
  const val = process.env[key];
  if (flagEnabled(val)) {
    fail(`${label} (${key}) is still enabled — must be off for production`);
  } else {
    pass(`${label} is disabled`);
  }
}

// ── C. Sound assets ───────────────────────────────────────────────────────────

console.log("\n[C] Sound assets");

const SOUNDS_DIR = join(ROOT, "assets", "sounds");
const REQUIRED_SOUNDS = ["swipe_right.mp3", "swipe_left.mp3", "match.mp3", "message_ping.mp3"];
// Silent placeholder files generated by ffmpeg are ~981 bytes.
// Real audio should be larger. Flag anything under 5 KB as likely placeholder.
const PLACEHOLDER_SIZE_THRESHOLD = 5 * 1024;

for (const name of REQUIRED_SOUNDS) {
  const p = join(SOUNDS_DIR, name);
  if (!existsSync(p)) {
    fail(`Missing sound asset: assets/sounds/${name}`);
  } else {
    const size = statSync(p).size;
    if (size < PLACEHOLDER_SIZE_THRESHOLD) {
      warn(`assets/sounds/${name} is ${size} bytes — looks like a silent placeholder. Replace with real audio before shipping.`);
    } else {
      pass(`assets/sounds/${name} (${(size / 1024).toFixed(1)} KB)`);
    }
  }
}

// ── D. Firebase native config files ──────────────────────────────────────────

console.log("\n[D] Firebase native config files");

const firebaseFiles = [
  { path: join(ROOT, "google-services.json"), platform: "Android" },
  { path: join(ROOT, "GoogleService-Info.plist"), platform: "iOS" },
];

for (const { path: p, platform } of firebaseFiles) {
  if (!existsSync(p)) {
    fail(`Missing ${platform} Firebase config: ${relative(ROOT, p)} — download from Firebase Console → Project settings → Your apps`);
  } else {
    const content = readFileSync(p, "utf8");
    if (
      content.includes("YOUR_PROJECT") ||
      content.includes("PLACEHOLDER") ||
      content.includes('"project_id": ""')
    ) {
      fail(`${relative(ROOT, p)} appears to contain placeholder values`);
    } else {
      pass(`${relative(ROOT, p)} present`);
    }
  }
}

// ── E. eas.json production profile ───────────────────────────────────────────

console.log("\n[E] eas.json production profile");

const easPath = join(ROOT, "eas.json");
const eas = readJson(easPath);

if (!eas) {
  fail("eas.json not found or invalid JSON");
} else {
  const prod = eas?.build?.production;
  if (!prod) {
    fail("eas.json: missing build.production profile");
  } else {
    pass("build.production profile exists");
    if (!prod.env || Object.keys(prod.env).length === 0) {
      warn("eas.json build.production.env is empty — ensure env vars are injected via EAS Secrets or CI");
    } else {
      pass(`build.production.env has ${Object.keys(prod.env).length} key(s)`);
      // Check for lingering placeholder values in eas.json env block
      for (const [k, v] of Object.entries(prod.env)) {
        if (typeof v === "string" && (v.includes("YOUR_") || v.includes("PLACEHOLDER") || v === "TODO")) {
          fail(`eas.json build.production.env.${k} contains placeholder value: "${v}"`);
        }
      }
      for (const [key, label] of Object.entries(devFlags)) {
        if (flagEnabled(prod.env[key])) {
          fail(`eas.json build.production.env.${key} enables ${label} - must be off for production`);
        }
      }
    }
    if (prod.channel && prod.channel !== "production") {
      warn(`eas.json build.production.channel is "${prod.channel}" — expected "production"`);
    }
  }
}

// ── F. No hardcoded localhost in source ───────────────────────────────────────

console.log("\n[F] Hardcoded localhost / 127.0.0.1");

const LOCALHOST_RE = /['"`](https?:\/\/(?:localhost|127\.0\.0\.1))[^'"`]*/g;
const srcFiles = collectSrc(ROOT);
let localhostHits = 0;

for (const file of srcFiles) {
  const rel = relative(ROOT, file);
  // Allow localhost in test files, scripts, and known dev-only guards
  if (rel.startsWith("__tests__") || rel.startsWith("scripts") || rel.includes(".test.")) continue;
  const content = readFileSync(file, "utf8");
  const matches = [...content.matchAll(LOCALHOST_RE)];
  for (const m of matches) {
    // Allow if inside a __DEV__ block (best-effort heuristic: within 3 lines of __DEV__)
    const lineNo = content.slice(0, m.index).split("\n").length;
    const lines = content.split("\n");
    const contextStart = Math.max(0, lineNo - 3);
    const context = lines.slice(contextStart, lineNo + 1).join(" ");
    if (context.includes("__DEV__") || context.includes("isDev") || context.includes("// dev")) continue;
    fail(`Hardcoded localhost in ${rel}:${lineNo} — "${m[0].slice(0, 60)}"`);
    localhostHits++;
    if (localhostHits >= 10) break; // Don't flood output
  }
}

if (localhostHits === 0) pass("No hardcoded localhost found in source files");

// ── G. TODO/FIXME in critical paths ──────────────────────────────────────────

console.log("\n[G] TODO/FIXME in critical production files");

const CRITICAL_FILES = [
  "app/(tabs)/index.tsx",
  "app/(tabs)/matches.tsx",
  "app/chat/[matchId].tsx",
  "components/DatingMatchModal.tsx",
  "lib/sounds.ts",
  "lib/swipeCounter.ts",
  "lib/routes.ts",
  "contexts/DatingMatchContext.tsx",
];

const TODO_RE = /\b(TODO|FIXME|HACK|XXX)\b/;

for (const rel of CRITICAL_FILES) {
  const p = join(ROOT, rel);
  if (!existsSync(p)) { warn(`Critical file not found: ${rel}`); continue; }
  const lines = readFileSync(p, "utf8").split("\n");
  const hits = lines
    .map((line, i) => ({ line, no: i + 1 }))
    .filter(({ line }) => TODO_RE.test(line) && !line.trim().startsWith("//  eslint"));
  if (hits.length > 0) {
    for (const { line, no } of hits.slice(0, 3)) {
      warn(`${rel}:${no} — ${line.trim().slice(0, 80)}`);
    }
  } else {
    pass(`${rel} — clean`);
  }
}

// ── H. app.json required fields ───────────────────────────────────────────────

console.log("\n[H] app.json required fields");

const appJson = readJson(join(ROOT, "app.json"));
const expo = appJson?.expo;

if (!expo) {
  fail("app.json missing or has no .expo key");
} else {
  const checks = [
    ["name",                      expo.name],
    ["slug",                      expo.slug],
    ["version",                   expo.version],
    ["ios.bundleIdentifier",      expo.ios?.bundleIdentifier],
    ["android.package",           expo.android?.package],
    ["ios.googleServicesFile",    expo.ios?.googleServicesFile],
    ["android.googleServicesFile",expo.android?.googleServicesFile],
  ];
  for (const [field, val] of checks) {
    if (!val) {
      fail(`app.json expo.${field} is missing`);
    } else if (String(val).includes("YOUR_") || String(val).includes("com.example")) {
      fail(`app.json expo.${field} looks like a placeholder: "${val}"`);
    } else {
      pass(`expo.${field} = "${val}"`);
    }
  }
}

// ── I. No committed .env files with secrets ───────────────────────────────────

console.log("\n[I] Committed .env files");

const dotEnvFiles = [".env", ".env.local", ".env.production", ".env.development"];
for (const name of dotEnvFiles) {
  const p = join(ROOT, name);
  if (existsSync(p)) {
    const content = readFileSync(p, "utf8");
    // If file has real-looking secret values (not just comments/placeholders)
    if (/=\S{10,}/.test(content) && !content.includes("PLACEHOLDER")) {
      warn(`${name} exists and may contain real secrets — ensure it is in .gitignore`);
    }
  }
}
pass(".env files checked");

// ── J. TypeScript ─────────────────────────────────────────────────────────────

console.log("\n[J] TypeScript compilation");

try {
  // Use local tsc if available, otherwise skip
  const tscPath = join(ROOT, "node_modules", ".bin", "tsc");
  if (existsSync(tscPath)) {
    const result = execSync(`"${tscPath}" --noEmit --skipLibCheck 2>&1`, {
      cwd: ROOT,
      encoding: "utf8",
      timeout: 60_000,
    });
    const errors = (result.match(/error TS\d+/g) ?? []).length;
    if (errors > 0) {
      fail(`TypeScript: ${errors} error(s) found`);
    } else {
      pass("TypeScript: 0 errors");
    }
  } else {
    // node_modules not installed — skip but note it
    warn("TypeScript check skipped (node_modules not installed in this environment). Run `tsc --noEmit` locally.");
  }
} catch (e) {
  warn(`TypeScript check could not run: ${e.message?.slice(0, 80)}`);
}

// ── Summary ───────────────────────────────────────────────────────────────────

console.log("\n" + "─".repeat(60));

if (warnings.length > 0) {
  console.log(`\n⚠  ${warnings.length} warning(s):`);
  warnings.forEach((w) => console.log(w));
}

if (failures.length > 0) {
  console.error(`\n✗  Launch check FAILED — ${failures.length} issue(s) must be resolved before shipping:\n`);
  failures.forEach((f) => console.error(f));
  console.error("\nFix the above issues, then re-run: node scripts/launch-check.mjs\n");
  process.exit(1);
} else {
  console.log(`\n✓  Launch check passed${warnings.length > 0 ? " (with warnings — review before submitting)" : " — you're good to ship! 🚀"}\n`);
  process.exit(0);
}
