import express, { Router, type IRouter } from "express";
import healthRouter from "./health";
import profilesRouter from "./profiles";
import discoveryRouter from "./discovery";
import matchesRouter from "./matches";
import messagesRouter from "./messages";
import subscriptionsRouter from "./subscriptions";
import reportsRouter from "./reports";
import dashboardRouter from "./dashboard";
import storageRouter from "./storage";
import resumeRouter from "./resume";
import authServerRouter from "./authServer";
import bioRouter from "./bio";
import eventsRouter from "./events";
import venuesRouter from "./venues";
import friendsRouter from "./friends";
import datingRouter from "./dating";
import doubleDateRouter from "./doubleDate";
import notificationsRouter from "./notifications";
import accountRouter from "./account";
import meRouter from "./me";
import icebreakersRouter from "./icebreakers";
import dailySparkRouter from "./dailySpark";
import antiGhostNudgeRouter from "./antiGhostNudge";
import aiChatRouter from "./aiChat";
import momentsRouter from "./moments";

const router: IRouter = Router();

router.use((req, res, next) => {
  return express.json({ limit: "15mb" })(req, res, next);
});

router.use(healthRouter);
router.use(profilesRouter);
router.use(discoveryRouter);
router.use(matchesRouter);
router.use(datingRouter);
router.use(doubleDateRouter);
router.use(friendsRouter);
router.use(messagesRouter);
router.use(subscriptionsRouter);
router.use(reportsRouter);
router.use(dashboardRouter);
router.use(storageRouter);
router.use(resumeRouter);
router.use(authServerRouter);
router.use(bioRouter);
router.use(eventsRouter);
router.use(venuesRouter);
router.use(notificationsRouter);
router.use(accountRouter);
router.use(meRouter);
router.use(icebreakersRouter);
router.use(dailySparkRouter);
router.use(antiGhostNudgeRouter);
router.use(aiChatRouter);
router.use(momentsRouter);

export default router;
