// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/onboarding/Step1.tsx": () => import("../components/mockups/onboarding/Step1.tsx"),
  "./components/mockups/onboarding/Step2.tsx": () => import("../components/mockups/onboarding/Step2.tsx"),
  "./components/mockups/onboarding/Step3.tsx": () => import("../components/mockups/onboarding/Step3.tsx"),
  "./components/mockups/onboarding/Step4.tsx": () => import("../components/mockups/onboarding/Step4.tsx"),
  "./components/mockups/onboarding/Step5.tsx": () => import("../components/mockups/onboarding/Step5.tsx"),
  "./components/mockups/signup/CinematicDark.tsx": () => import("../components/mockups/signup/CinematicDark.tsx"),
  "./components/mockups/signup/CleanModern.tsx": () => import("../components/mockups/signup/CleanModern.tsx"),
  "./components/mockups/signup/GradientImmersive.tsx": () => import("../components/mockups/signup/GradientImmersive.tsx"),
  "./components/mockups/location/VariantA.tsx": () => import("../components/mockups/location/VariantA.tsx"),
  "./components/mockups/location/VariantB.tsx": () => import("../components/mockups/location/VariantB.tsx")
};
